### ISSUE TITLE
direct monitor routing matrix

### ISSUE THREAD

**Issue by Be-ing** [MrBollie/RME-Babyace-Pro-ALSA-Mixer-Patch#1]
Hi, I am very excited to see you have reverse engineered some of the Babyface Pro's mixer features. I have been using this audio interface to DJ since late 2015 and it works excellent with Linux except for one frustrating omission. There is no way to route a mono input to both sides of a stereo output for direct monitoring on the unit. I have hacked around this by using Y splitter cables on the inputs, which of course halves the number of inputs the interface can use. I have [asked RME about this](https://forum.rme-audio.de/viewtopic.php?pid=110865#p110865) on their forum [twice](https://forum.rme-audio.de/viewtopic.php?pid=132155#p132155) but they didn't care (despite the misleading advertising for the Babyface Pro as working with Linux and the manual saying the controls on the unit were sufficient). When I contacted their support, they told me to get an iPad (wtf?).

I will build a patched kernel to test this soon, but I have already built the [mixer GUI](https://github.com/MrBollie/bbfpromix) and looked through the patch and I don't see anything about the direct monitor routing. I don't care about all the fanciness of Totalmix FX with submixes and whatnot; all I want to do is be able to route any hardware input to any hardware output with an adjustable volume. In the GUI application we could create an easy way to control the levels of one input to both sides of a stereo output pair so the stereo image is balanced. If we want to get fancy we could even consider adding a pan knob.

This kernel stuff is above my head, but I would be happy to help with the GUI application. I have not worked with GTK or C before, but I have experience with Qt and C++.

**Comment by Be-ing** [comment]
How did you reverse engineer the mixer in class compliant mode? Did you use a hardware sniffer with an iOS device? I looked into running TotalMix FX on iOS in a VM and sniffing the USB traffic with Wireshark but it didn't seem possible to connect a USB device to an emulated iOS device.

**Comment by MrBollie** [comment]
Direct monitor routing is basically the main feature of the patch. ;) It is done by addressing the cross-points of the DSPs routing matrix and exposing them as alsa mixer controls. On my GUI, you can then select which pair of output channels you want to set the individual input levels and panning for. So that's a bit more high-level, and reduces the complexity of the 288 routing points. 

About the reverse-engineering: I also mentioned my plans on the RME forum, bought an http://openvizsla.org/ , started sniffing on the ipad<->BBF communication and discovered they are using sysex on an internal MIDI port to address the DSPs routing matrix, meters, and such. But that was when RME actually got in touch with me and hinted me an USB control endpoint, that I could use. And that's what ended up in the patch.

**Comment by Be-ing** [comment]
Ah okay, I think I was not understanding the design of the GUI. I was confused what the "Output" combobox in the bottom left did. So, if I understand correctly, the workflow is to select an output pair, then the vertical sliders control the direct monitoring of each input channel to that selected output pair and the horizontal sliders control the panning? If so, why are the outputs also listed going to other outputs? Why is there a slider for an output going to itself? Is that how you control the volume of that output? If not, is it possible to control the input and output volumes separately from the routing levels?

**Comment by Be-ing** [comment]
I think a more intuitive design for the GUI would be to present a matrix. Here is a screenshot of the web control interface on the MOTU Ultralite AVB:
![image](https://camo.githubusercontent.com/24a76cb700798c1fedbf8fb8dd5023e11e7dcabc/687474703a2f2f7777772e6d6f74752e636f6d2f74656368737570706f72742f696d616765732f746f74642f70696373666f72746970732f66726f6d636f6d707574657238746f616e616c6f672e706e67)

Then the volume and panning sliders could be exposed only after making the routing in the matrix.

(I ended up returning the MOTU Ultralite AVB because there was a [very ugly crackling noise](https://linuxmusicians.com/viewtopic.php?p=89922#p89922) it made at unpredictable times. Plus when I got better speakers (Genelec 8030A) I could clearly hear the Babyface Pro sounds better.)

> sysex on an internal MIDI port to address the DSPs routing matrix, meters, and such

Interesting, I emailed Fons Adriaensen, who also has a Babyface Pro, and he suggested this is how TotalMix FX on the iPad might work. I did some quick attempts sending the MIDI messages documented in the Babyface Pro manual (page 69) with amidi to control it, but those did not do anything as far as I could tell. I figured those MIDI messages were received by the TotalMix FX software on the computer which in turn controlled the Babyface Pro rather than directly manipulating the Babyface Pro.

I am pleasantly surprised RME was cooperative with you on this. They were dismissive when I tried to work with them.

**Comment by Be-ing** [comment]
By the way, maybe you want to post to the [Linux Musicians forum](https://linuxmusicians.com/viewforum.php?f=6) so others know about your work?

**Comment by Be-ing** [comment]
Also, I wonder how much work it would be to extend this for other modern RME audio interfaces. Perhaps RME would be willing to give you some so you could do this. I think it is worth asking them, especially now that the Babyface Pro support has been merged upstream and you've shown you have the skills to do it. It would be awesome if we could design the GUI application so one application could work for all of these devices. I would be happy to help with the GUI application. It would be good for me to get some GTK experience.

**Comment by Be-ing** [comment]
I'll close this in favor of https://github.com/MrBollie/bbfpromix/issues/2 as this has more to do with the design of the GUI frontend.
