### ISSUE TITLE
Would you fancy a totalmix-like web control?

### ISSUE THREAD

**Issue by spiregarden** [MrBollie/RME-Babyace-Pro-ALSA-Mixer-Patch#10]
Salutes for MrBollie for an outstanding work! You've sure done the heavy lifting with this project.

Wouldn't it be cool to have a python program connected to alsa api and the internal midi of RME, while offering access to those via websocket. Then the UI could be done with pure javascript, so it could be ran in browser, either on your own pc, or over network.

If anyone's with me, we could schedule a video call and spend at least one evening (CET) programming. I could take the challenge of either the python program or the JS frontend, although I think I'd be better with the JS side.

Naturally, it would help if RME would provide us with the sysex command table of the internal midi, and that missing USB end points for persistent storage, but we don't know if that's gonna happen.

**Comment by Be-ing** [comment]
A nicer GUI would be great! I'd write it in Rust, but I have enough projects currently and am not about to take up another. Please let us know when you have something ready to test. :)

**Comment by MrBollie** [comment]
Thank you for the kind words, @spiregarden . While anyone is welcome to create a proper alsa frontend for that particular audio interface, it is outside the scope of this repository.

**Comment by spiregarden** [comment]
@MrBollie: Regarding your work on the Alsa patch, could you point me to the right direction, do you think the mixer status would be available from the same USB endpoint? And could the addresses be guessed without RME's assistance?

**Comment by Be-ing** [comment]
@spiregarden I wrote a [post](https://linuxmusicians.com/viewtopic.php?p=144074#p144074) outlining my thoughts how to go about this. I think we can reverse engineer the unknown aspects by intercepting USB traffic in a Windows VM using Wireshark on the Linux host.

**Comment by spiregarden** [comment]
Nice!! We'll continue our discussion there.
