### ISSUE TITLE
save routing state to device persistently

### ISSUE THREAD

**Issue by Be-ing** [MrBollie/RME-Babyace-Pro-ALSA-Mixer-Patch#5]
Routing can be set up with the GUI mixer application, but somehow it is not stored persistently in the Babyface Pro's memory. It is capable of storing this state, even in class compliant mode. This can be easily verified by using the buttons and wheel on the device to configure a routing, unplugging the device so it loses power, then plugging it back in.

**Comment by MrBollie** [comment]
RME hasn't provided me with USB requests to do that, so it's not possible right now. Communication to iPad takes a completely different approach, that cannot be implemented as a mixer quirk.

**Comment by Be-ing** [comment]
Would this require its own mixer implementation like sound/usb/mixer_scarlet.c?

**Comment by MrBollie** [comment]
No, that requires a specific control EP. I've asked RME about this, but they can't provide it.

**Comment by Be-ing** [comment]
It turns out state is saved persistently on the device already. I got confused because bbfpromix didn't initialize its state from the device on startup: https://github.com/MrBollie/bbfpromix/pull/7

**Comment by Be-ing** [comment]
Well some state is saved on the device... sometimes. I haven't quite figured out what is saved persistently and when.

**Comment by Be-ing** [comment]
Ah, I think I understand what's going on now. The state is not stored in the device; it is saved in ALSA mixer. This explains why bbfpromix can restore state when the application is restarted, but not when the device is replugged.
