### ISSUE TITLE
Control of input gain through USB ?

### ISSUE THREAD

**Issue by jharog** [MrBollie/RME-Babyace-Pro-ALSA-Mixer-Patch#7]
Hi,
First thank you for this work that definitively greatly improves the use of Babyface pro on linux. 
Is it possible to get access to channel 1 to 4 input gains this way (without having to use the rotating knob) for USB recording ?

**Comment by MrBollie** [comment]
No, unfortunately not, as RME hasn't provided mit with a way of doing that.
