### ISSUE TITLE
Translation to Babyface (non-pro)

### ISSUE THREAD

**Issue by Burtan** [MrBollie/RME-Babyace-Pro-ALSA-Mixer-Patch#9]
Hi,

I'm owning a RME Babyface (non-pro) and I'm also interested in using it on linux. I read you contacted RME about information regarding the RME Babyface Pro/FS. Did they say anything about similiarities/differences comparing the Pro/non-pro version? I guess that not many changes would be needed to make this patch also apply to the RME Babyface non-pro.

**Comment by Be-ing** [comment]
I think the original Babyface is a completely different device than the Babyface Pro, so this patch likely doesn't help at all for the original Babyface. The Babyface Pro and Babyface Pro FS are almost the same device and present with the same USB descriptors.

**Comment by Burtan** [comment]
I secretely hoped that I only have to adept the inputs/outputs (Babyface non pro is 10/12), maybe adept some numbers on the const parameters. But this sounds that I have to dig deep into the alsa api? And get information from RME... :D

**Comment by MrBollie** [comment]
@Burtan Try on their forum.
